### PR TITLE
upgrade to ng 18 and modernize

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
* updated Angular to v 18
* switched to standalone components
* switched DI to use `inject` function

### CODE REVIEW

**Review by abashmak — COMMENTED** [review]
Question before I test this out. I see that `yarn.lock` was deleted and `package-lock.json` was added. Are we changing from yarn to npm for the build?

**Comment by DmitryEfimenko** [comment]
Yeah, I don't remember if you have instructions in the readme reference yarn. But yes, just use `npm i`

**Review by abashmak — COMMENTED** [review]
```bash
root@opp-web# git checkout feat/modernize
Branch 'feat/modernize' set up to track remote branch 'feat/modernize' from 'origin'.
Switched to a new branch 'feat/modernize'
root@opp-web# rm -rf node_modules/
root@opp-web# npm i
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @angular/compiler@18.2.11
npm error Found: @angular/core@18.2.8
npm error node_modules/@angular/core
npm error   @angular/core@"^18.2.8" from the root project
npm error   peer @angular/core@"18.2.8" from @angular/animations@18.2.8
npm error   node_modules/@angular/animations
npm error     @angular/animations@"^18.2.8" from the root project
npm error     peer @angular/animations@"^17.0.0 || ^18.0.0" from @angular/material@17.2.1
npm error     node_modules/@angular/material
npm error       @angular/material@"^17.2.1" from the root project
npm error     1 more (@angular/platform-browser)
npm error   12 more (@angular/cdk, @angular/common, @angular/forms, ...)
```

node version: v20.17.0

**Comment by abashmak** [comment]
I was able to get around above error by running: `npm install --save --legacy-peer-deps`. Afterwards, it compiled and deployed successfully to: https://openpassphrase.com/demo. But I think npm installation should be fixed before merging.

**Review by abashmak — APPROVED** [review]

**Review by abashmak — APPROVED** [review]
Thanks for making this change!

**Pull request merged**
