### PR TITLE
feat(search): allow searching on mobile

### LINKED ISSUE #63: Searching on PWA (mobile clients)
As a user of the PWA app on a mobile client, I'd like to be able to search through categories and items by typing in a search box. The search box may be implemented as an expandable icon, similar to: https://codepen.io/912lab/pen/LsplC

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
* closes #63 
* created an expandable-input-cdk component
  - this component does not implement any styling, which makes it easy to reuse between projects
  - Eventually I'll move this into its own package and publish it to npm. It's too good not to share :)
* created an expandable-input specifically for opp
  - this component uses the cdk and implements material styling for it
  - also a great candidate for a dedicated package
* introduced a separate route for entering secret phrase
  - as opposed to having it on the same route as categories
* changed the appearance of "expand all" button. Now it just looks like an icon rather than a fab button, which conforms to the material spec.

### CODE REVIEW

**Comment by abashmak** [comment]
Find some minor bugs:

1. After searching, there is no way to clear the search and go back to collapsed view. If using backspace to clear the search field, all categories end up expanded.
2. When using backspace to clear, the app freezes on the last 2 characters for a very noticeable amount of time (~2 seconds).

**Comment by DmitryEfimenko** [comment]
it was a matter of missing exclamation mark... should work now

**Comment by DmitryEfimenko** [comment]
updated behavior as discussed

**Comment by abashmak** [comment]
Are the two issues I mention above also fixed?

**Comment by abashmak** [comment]
Deployed and tested:

1. Mobile issues still remain
2. Search by typing still enabled in desktop version and the search control is missing

**Comment by DmitryEfimenko** [comment]
sounds like you didn't really deploy. Check again please

**Pull request merged**
